services:
  db:
    image: mariadb:12.3
    environment:
      MARIADB_DATABASE: horaire
      MARIADB_USER: louisbrqn
      MARIADB_PASSWORD: Super
      MARIADB_ROOT_PASSWORD: Super
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"

volumes:
  db_data:
